[package]
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
name = "bformulae"
version = "0.1.0"

[dependencies]
cryptominisat = "0.1.0"
log = "0.3.6"
maplit = "0.1.3"

[dev-dependencies]
env_logger = "0.3.3"
quickcheck = "0.2.27"
rand = "0.3.14"
