[package]
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
name = "bformulae"
version = "0.1.0"

[dependencies]
log = "0.3.6"
maplit = "0.1.3"
sat = { git = "https://github.com/cstorey/sat.git" }

[dev-dependencies]
quickcheck = "0.2.27"
rand = "0.3.14"
env_logger = "0.3.3"
